### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by ethernetdan**

### CODE REVIEW

**Comment by anubiann00b** [comment]
This isn't *quite* a bugfix.

**Comment by zfogg** [comment]
+1
thanks Dan :+1:

**Comment by zfogg** [comment]
+1 :+1:
thanks @ethernetdan

**Comment by jhil** [comment]
Any updates here?

**Comment by zfogg** [comment]
it's fixed

**Review by paaqp — APPROVED** [review]

**Review by paaqp — APPROVED** [review]

**Pull request closed without merging**
